sudo: required

language: node_js

node_js:
  - "node"

services:
  - docker

env:
  matrix:
    - PHP_VERSION=54 WP_VERSION=latest WP_MULTISITE=0
    - PHP_VERSION=55 WP_VERSION=latest WP_MULTISITE=0
    - PHP_VERSION=56 WP_VERSION=latest WP_MULTISITE=0
    - PHP_VERSION=70 WP_VERSION=latest WP_MULTISITE=0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install docker-engine --no-install-recommends -y -o Dpkg::Options::="--force-confmiss" -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.8.0-rc2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/
  - docker-compose -v
  - docker -v

install:
  - npm run build

script:
  - npm run unittest:js
  - npm run composer && npm run unittest:php${PHP_VERSION}