sudo: required

language: node

services:
  - docker

env:
  matrix:
    - PHP_VERSION=54 WP_VERSION=latest WP_MULTISITE=0
    - PHP_VERSION=55 WP_VERSION=latest WP_MULTISITE=0
    - PHP_VERSION=56 WP_VERSION=latest WP_MULTISITE=0
    - PHP_VERSION=70 WP_VERSION=latest WP_MULTISITE=0


before_install:
  - npm run build

script:
  - npm run unittest:js
  - npm run composer && npm run unittest:php$PHP_VERSION