language: php

php:
  - 5.4

addons:
  hosts:
    - woopos.dev

env:
  - WP_VERSION=latest WP_MULTISITE=0
  #    - WP_VERSION=latest WP_MULTISITE=1
  #    - WP_VERSION=3.8 WP_MULTISITE=0
  #    - WP_VERSION=3.8 WP_MULTISITE=1

before_install:
  - git submodule update --init --recursive

install:
  # php libraries
  - composer require satooshi/php-coveralls:~0.6.1@stable
  - composer require guzzlehttp/guzzle:~5
  # install wordpress & woocommerce
  - bash tests/unit/php/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - mkdir /tmp/wordpress/wp-content/plugins/woocommerce-pos/
  - mv * .[^.]* /tmp/wordpress/wp-content/plugins/woocommerce-pos/
  - mv /tmp/wordpress/* ./
  - cd wp-content/plugins/woocommerce-pos/
  # apache
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f tests/unit/php/bin/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

before_script:
  - npm install -g grunt-cli
  - npm install

script:
  - grunt test
  - phpunit -c phpunit.xml.dist
  #    - ./node_modules/.bin/pioneer

after_success:
  - php vendor/bin/coveralls -v
  - grunt mochacov:coverage